<?php

namespace Xedi\SendGrid\Exceptions\Domain;

use GuzzleHttp\Exceptions\GuzzleException;
use UnexpectedValueException;
use Xedi\SendGrid\Contracts\Exception as ExceptionContract;

/**
 * Represents a failure to decode the json within a response
 * @package Xedi\SendGrid\Exception\Domain
 */
class FailedDecodingException extends UnexpectedValueException implements ExceptionContract
{
    /**
     * @param string          $json_error_msg The error generated by libcjson
     * @param int             $code           The Status Code to return
     * @param GuzzleException $previous       Original Exception
     */
    public function __construct(string $json_error_msg, int $code, GuzzleException $previous)
    {
        parent::__construct(
            "A json_decode exception [{$json_error_msg}] occurred whilst " +
            "trying to decode the errors in the attached exception",
            $code,
            $previous
        );
    }
}
